### ISSUE TITLE
galera register crashes if mysql unresponsive or error

### ISSUE THREAD

**Issue by akuzminsky** [twindb/proxysql-tools#23]
* ProxySQL Tools version:

### Description

If MySQL node is not available of whatever reason (no connection, too many connections, other error) `proxysql-tool galera register` crashes with stack
```
2017-05-31 11:21:37,105: ERROR: galera_manager.refresh_and_validate_node_state():116: Node 10.0.52.98:3306 state could not be fetched
Traceback (most recent call last):
  File "/bin/proxysql-tool", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/proxysql_tools/cli.py", line 128, in register
    galera_cfg):
  File "/usr/lib/python2.7/site-packages/proxysql_tools/galera.py", line 39, in register_cluster_with_proxysql
    galera_man = fetch_galera_manager(galera_cfg)
  File "/usr/lib/python2.7/site-packages/proxysql_tools/galera.py", line 287, in fetch_galera_manager
    galera_man.discover_cluster_nodes()
  File "/usr/lib/python2.7/site-packages/proxysql_tools/managers/galera_manager.py", line 49, in discover_cluster_nodes
    self.refresh_and_validate_node_state(initial_node)
  File "/usr/lib/python2.7/site-packages/proxysql_tools/managers/galera_manager.py", line 117, in refresh_and_validate_node_state
    raise GaleraNodeUnknownState(e.messages)
AttributeError: 'OperationalError' object has no attribute 'messages'
```

**Comment by akuzminsky** [comment]
Fixed in 0.3.0
