### ISSUE TITLE
Gracefull handle empty backends list

### ISSUE THREAD

**Issue by akuzminsky** [twindb/proxysql-tools#36]
* ProxySQL Tools version: 0.3.9

### Description

If `mysql_servers` table is empty `proxysql-tool` crashes. It should just throw a warning message.

### What I Did

```
# proxysql-tool galera server status
2017-07-10 00:18:41,949: INFO: server.server_status():31: Writers:
Traceback (most recent call last):
  File "/bin/proxysql-tool", line 9, in <module>
    load_entry_point('proxysql-tools==0.3.9', 'console_scripts', 'proxysql-tool')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/proxysql_tools/cli.py", line 140, in status
    server_status(cfg)
  File "/usr/lib/python2.7/site-packages/proxysql_tools/galera/server.py", line 32, in server_status
    for backend in proxysql.find_backends(hostgroup_id):
  File "/usr/lib/python2.7/site-packages/proxysql_tools/proxysql/proxysql.py", line 316, in find_backends
    raise ProxySQLBackendNotFound('Can not find any backends')
proxysql_tools.proxysql.exceptions.ProxySQLBackendNotFound: Can not find any backends
[root@proxysql vagrant]#
```

**Comment by mkryva** [comment]
https://github.com/twindb/proxysql-tools/pull/43
Review please.
